apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wiz-deploy
  name: wiz-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiz-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wiz-deploy
    spec:
      containers:
      - image: ash2code/node-wizapp:v5
        name: node-wizapp
        resources: {}
status: {}
